### ISSUE TITLE
Strange syntax in README sample?

### ISSUE THREAD

**Issue by goloroden** [jproulx/node-custom-error#3]
In the `README.md`, there is an example that says:

```javascript
var ValidationError = createCustomError('ValidationError', { 'required', 'Missing parameter x' }, TypeError);
```

What is the second parameter?

To me, ```{ 'required', 'Missing parameter x' }``` doesn't look like valid JavaScript syntax, but further below you write something about object descriptors. When I google for that, I only find information on enumerables, …

Can you explain whether this is a syntax error, or what kind of language construct this is?

This would be very helpful :-)

**Comment by jproulx** [comment]
Just a typo, will fix to use proper object notation.
